<p>catch 捕获 observable 中的错误，可以通过返回一个新的 observable 或者抛出错误对象来处理。</p>

<span class="btn" (click)="catchDemo()">catch</span>
<span class="btn" (click)="catchRetryDemo()">catch 重试</span>
